// Mock PRD data for demo/preview purposes

export const DEMO_PRID = "demo-prd-001";

export const DEMO_PRD_CONTENT: Record<string, string> = {
  "Executive Summary":
    "FoodFlow adalah platform SaaS yang menghubungkan restoran dengan supplier bahan baku melalui marketplace B2B yang transparan dan efisien. Platform ini memungkinkan restoran untuk membandingkan harga, memesan bahan baku, dan mengelola inventori dalam satu dashboard. Didukung AI untuk prediksi kebutuhan stok dan optimalisasi rantai pasok.\n\n**Value Proposition:** Mengurangi biaya bahan baku hingga 15% melalui price comparison & bulk ordering, menghemat waktu procurement 4 jam/minggu, dan mengurangi food waste 20% melalui prediksi inventori berbasis AI.",
  "Problem Statement":
    "**Current State:** Restoran di Indonesia masih mengandalkan WhatsApp/telepon untuk memesan bahan baku ke supplier. Tidak ada price transparency — restoran kecil sering dapat harga lebih mahal. Supplier juga kesulitan mengelola puluhan pesanan harian dari berbagai channel.\n\n**Pain Points:**\n- Restoran harus chat 5-10 supplier tiap pagi hanya untuk bandingkan harga\n- Tidak ada standarisasi kualitas — bahan datang kadang tidak sesuai\n- Supplier kehilangan ~30% potential order karena ribetnya proses manual\n- Inventori restoran sering overstock/understock karena tidak ada data\n- Owner restoran tidak punya visibilitas ke spending bahan baku per bulan",
  "Product Vision & OKRs":
    "**Vision:** Menjadi sistem operasi rantai pasok untuk industri F&B di Asia Tenggara — di mana setiap restoran dan supplier terhubung dalam satu ekosistem yang efisien.\n\n| Objective | Key Results | Target |\n|-----------|-------------|--------|\n| Adopsi restoran | Jumlah restoran aktif dalam 90 hari | ≥ 200 restoran |\n| Supplier onboarding | Supplier terdaftar dengan katalog produk | ≥ 50 supplier |\n| Transaction volume | Total GMV melalui platform | ≥ Rp 2M/bulan |\n| Retensi | Restoran yang repeat order dalam 30 hari | ≥ 60% |\n| Cost reduction | Rata-rata penghematan biaya bahan per restoran | ≥ 10% |",
  "Target Users & Personas":
    "### Persona 1: Bu Sari — Pemilik Restoran Menengah\n- **Demographic:** 35-50 tahun, pemilik 3-5 cabang restoran\n- **Goals:** Hemat biaya bahan baku, efisiensi proses order, quality control\n- **Pain Points:** Admin order manual tiap pagi, supplier tidak konsisten, tidak tahu total spending\n\n### Persona 2: Pak Rudi — Supplier Bahan Makanan\n- **Demographic:** 30-55 tahun, distributor bahan makanan\n- **Goals:** Perluas customer base, efisiensi proses order, kurangi kesalahan order\n- **Pain Points:** Order via WA berceceran, susah track pesanan, restoran sering cancel mendadak\n\n### Persona 3: Dina — Kitchen Manager\n- **Demographic:** 25-35 tahun, kitchen manager di restoran\n- **Goals:** Pastikan stok selalu cukup, kurangi food waste, efisiensi inventori\n- **Pain Points:** Stok habis mendadak, bahan expired, tidak ada forecast kebutuhan",
  "User Stories":
    "| ID | User Story | Acceptance Criteria | Priority |\n|----|-----------|---------------------|----------|\n| US-01 | Sebagai owner restoran, saya ingin membandingkan harga bahan dari multiple supplier dalam satu layar | Tabel perbandingan harga real-time, filter per kategori, history harga | P0 |\n| US-02 | Sebagai kitchen manager, saya ingin mendapat prediksi kebutuhan stok mingguan berdasarkan data historis | Dashboard forecast, alert stok menipis, rekomendasi order quantity | P0 |\n| US-03 | Sebagai supplier, saya ingin upload katalog produk dan update stok real-time | Upload CSV/image, auto-update stok, notifikasi order masuk | P0 |",
  "User Flow & Journey":
    '```mermaid\nflowchart LR\n    A(["🚀 Mulai"]) --> B["👤 Register Restoran"]\n    B --> C{"🔀 Verifikasi Akun"}\n    C -->|"valid"| D["🛒 Bandingkan Harga Supplier"]\n    C -->|"gagal"| B\n    D --> E["📝 Buat Purchase Order"]\n    E --> F{{"🧠 AI Forecast Stok"}}\n    F --> G[("🗄 Simpan Order")]\n    G --> H["📊 Skor & Insight"]\n    H --> I(["✅ Selesai"])\n    class A,I se\n    class B,C auth\n    class D,E user\n    class F ai\n    class G db\n    class H feedback\n    classDef user fill:#13335c,stroke:#3b82f6,color:#dbeafe,stroke-width:1.5px;\n    classDef ai fill:#2e1065,stroke:#8b5cf6,color:#ede9fe,stroke-width:1.5px;\n    classDef db fill:#0a3d2e,stroke:#10b981,color:#d1fae5,stroke-width:1.5px;\n    classDef feedback fill:#5c2c0a,stroke:#f97316,color:#ffedd5,stroke-width:1.5px;\n    classDef auth fill:#4a1535,stroke:#ec4899,color:#fce7f3,stroke-width:1.5px;\n    classDef se fill:#3b1f6e,stroke:#a78bfa,color:#f5f3ff,stroke-width:2px;\n```',
  "Feature List (MoSCoW)":
    "| Priority | Feature | Description | Effort |\n|----------|---------|-------------|--------|\n| **Must Have** | Supplier Marketplace | Bandingkan harga & order dari multiple supplier | L |\n| **Must Have** | Order Management | Buat PO, tracking, konfirmasi, history | L |\n| **Must Have** | Inventory Dashboard | Stok real-time, alert, forecast | M |\n| **Must Have** | AI Demand Forecasting | Prediksi kebutuhan berdasarkan histori + tren | L |\n| **Should Have** | Mobile App (Supplier) | Supplier bisa konfirmasi & update via mobile | M |\n| **Should Have** | Payment Integration | Escrow payment, invoice otomatis | M |\n| **Could Have** | Menu Engineering | Analisis profitabilitas per menu item | S |",
  "System Architecture":
    '```mermaid\nflowchart LR\n    subgraph Client["🖥 Client Layer"]\n        UI["📱 Restoran Dashboard"]\n        SUP["📲 Supplier App"]\n    end\n    subgraph Core["⚙️ Backend Services"]\n        GW["🚪 API Gateway"]\n        ORD["📦 Order Service"]\n        AIF{{"🧠 AI Forecasting"}}\n    end\n    subgraph Data["🗄 Data Layer"]\n        PG[("🗄 PostgreSQL")]\n        RD[("⚡ Redis Cache")]\n    end\n    UI --> GW\n    SUP --> GW\n    GW --> ORD\n    ORD --> AIF\n    ORD --> PG\n    ORD --> RD\n    AIF --> PG\n    class UI,SUP user\n    class GW,ORD feedback\n    class AIF ai\n    class PG,RD db\n    classDef user fill:#13335c,stroke:#3b82f6,color:#dbeafe,stroke-width:1.5px;\n    classDef ai fill:#2e1065,stroke:#8b5cf6,color:#ede9fe,stroke-width:1.5px;\n    classDef db fill:#0a3d2e,stroke:#10b981,color:#d1fae5,stroke-width:1.5px;\n    classDef feedback fill:#5c2c0a,stroke:#f97316,color:#ffedd5,stroke-width:1.5px;\n    classDef auth fill:#4a1535,stroke:#ec4899,color:#fce7f3,stroke-width:1.5px;\n    classDef se fill:#3b1f6e,stroke:#a78bfa,color:#f5f3ff,stroke-width:2px;\n```',
  "Use Case Diagram":
    '```mermaid\nflowchart LR\n    R1(["👤 Restoran Owner"])\n    R2(["👨‍🍳 Kitchen Manager"])\n    R3(["🚚 Supplier"])\n    UC1["🛒 Bandingkan Harga"]\n    UC2["📝 Buat Purchase Order"]\n    UC3["📦 Kelola Inventori"]\n    UC4{{"🧠 Lihat AI Forecast"}}\n    UC5["📤 Upload Katalog"]\n    R1 --> UC1\n    R1 --> UC2\n    R2 --> UC3\n    R2 --> UC4\n    R3 --> UC5\n    class R1,R2,R3 se\n    class UC1,UC2,UC3 user\n    class UC4 ai\n    class UC5 feedback\n    classDef user fill:#13335c,stroke:#3b82f6,color:#dbeafe,stroke-width:1.5px;\n    classDef ai fill:#2e1065,stroke:#8b5cf6,color:#ede9fe,stroke-width:1.5px;\n    classDef db fill:#0a3d2e,stroke:#10b981,color:#d1fae5,stroke-width:1.5px;\n    classDef feedback fill:#5c2c0a,stroke:#f97316,color:#ffedd5,stroke-width:1.5px;\n    classDef auth fill:#4a1535,stroke:#ec4899,color:#fce7f3,stroke-width:1.5px;\n    classDef se fill:#3b1f6e,stroke:#a78bfa,color:#f5f3ff,stroke-width:2px;\n```',
  "Data Model (ERD)":
    '```mermaid\nerDiagram\n    RESTAURANT {\n        uuid id PK\n        string name\n        string address\n        jsonb settings\n    }\n    SUPPLIER {\n        uuid id PK\n        string company_name\n        jsonb catalog\n        float rating\n    }\n    PRODUCT {\n        uuid id PK\n        uuid supplier_id FK\n        string name\n        string category\n        decimal price_per_unit\n        string unit\n    }\n    ORDER {\n        uuid id PK\n        uuid restaurant_id FK\n        uuid supplier_id FK\n        enum status\n        decimal total_amount\n        timestamp created_at\n    }\n    ORDER_ITEM {\n        uuid id PK\n        uuid order_id FK\n        uuid product_id FK\n        int quantity\n        decimal unit_price\n    }\n    INVENTORY {\n        uuid id PK\n        uuid restaurant_id FK\n        uuid product_id FK\n        decimal current_stock\n        decimal min_threshold\n    }\n    RESTAURANT ||--o{ ORDER : places\n    SUPPLIER ||--o{ PRODUCT : supplies\n    SUPPLIER ||--o{ ORDER : fulfills\n    ORDER ||--o{ ORDER_ITEM : contains\n    PRODUCT ||--o{ ORDER_ITEM : ordered_as\n    RESTAURANT ||--o{ INVENTORY : tracks\n    PRODUCT ||--o{ INVENTORY : tracked_in\n```',
};

export const DEMO_PRD = {
  id: DEMO_PRID,
  title: "FoodFlow — B2B Marketplace Supplier Bahan Baku Restoran",
  description:
    "Platform SaaS yang menghubungkan restoran dengan supplier bahan baku melalui marketplace B2B. Fitur utama: price comparison, AI-powered demand forecasting, inventory management, dan automated ordering.",
  language: "id" as const,
  created_at: "2026-06-21T10:30:00Z",
  sections: Object.entries(DEMO_PRD_CONTENT).map(([title, content]) => ({
    title,
    content,
  })),
};
